// soluzioniData — bilingual content for solution detail pages.
// Each slug has top-level shared fields (icon, slug) and per-language content in .it / .en.

export const SOLUZIONI_DATA = {
  'tracciabilita-pallet': {
    n: '01',
    slug: '/soluzioni/tracciabilita-pallet',
    icon: 'pallet',
    it: {
      title: 'Tracciabilità Pallet & Asset',
      eyebrow: 'Soluzione · Tracciabilità Pallet & Asset',
      pitch: 'Tracciabilità completa di pallet, UDC e asset riutilizzabili, con visibilità in tempo reale e riconciliazione tra tutti gli attori della filiera.',
      intro: "La gestione dei pallet e, più in generale, delle unità di carico (UDC) e degli asset riutilizzabili è una delle aree più sensibili dei processi aziendali: scarsa visibilità sui flussi, disallineamenti tra consegnato, restituito e giacente, perdite economiche e contenziosi tra i diversi attori della filiera. LogiTrace è la soluzione LogiExpert che trasforma un processo dispersivo in un sistema organizzato, trasparente e pienamente controllabile.",
      statsLabel: 'In sintesi',
      stats: [
        { v: 'SaaS', l: 'Architettura web-based, attivazione rapida' },
        { v: 'ERP',  l: 'Integrazione nativa con i gestionali' },
        { v: 'ROI',  l: 'Ritorno sull’investimento rapido e misurabile' },
      ],
      problems: [
        { t: 'Visibilità limitata sui flussi', b: 'Senza strumenti strutturati manca una lettura chiara, tempestiva e condivisa dei movimenti degli asset tra i diversi attori della filiera.' },
        { t: 'Disallineamenti e mancati rientri', b: 'Differenze ricorrenti tra quanto consegnato, restituito e realmente in giacenza presso clienti, fornitori, vettori e piattaforme logistiche.' },
        { t: 'Perdite e contenziosi', b: 'Smarrimenti, dispersioni e contestazioni che si traducono in perdite economiche, costi amministrativi e tensioni tra le parti.' },
        { t: 'Gestione manuale e non integrata', b: 'Fogli e strumenti non integrati che non dialogano con i sistemi aziendali, limitando controllo e capacità decisionale.' },
      ],
      software: {
        name: 'LogiTrace',
        label: 'Software che realizza la soluzione',
        desc: "Piattaforma web-based in modalità SaaS per la tracciabilità completa e la gestione integrata degli asset riutilizzabili. Si integra con i principali ERP e gestionali ed è configurabile sui flussi reali dell'azienda. Oltre ai pallet gestisce ganci, box, cassette, rack e qualunque UDC che richieda tracciabilità, restituzione e compensazione.",
        bullets: [
          'Tracciamento puntuale dei movimenti degli asset tra aziende, clienti, distributori e partner logistici',
          'Monitoraggio in tempo reale di quantità consegnate, ricevute e giacenti per ciascun soggetto',
          'Generazione automatica dei buoni pallet / buoni asset a ogni consegna, come credito tracciato',
          'Estinzione dei buoni tramite riconsegna o meccanismi di compensazione tra le parti',
          'Gestione degli asset danneggiati: segnalazione, stato, responsabilità, recupero o addebito',
        ],
        sku: 'Architettura web-based · SaaS',
      },
      features: [
        { icon: 'radar',    t: 'Tracciabilità in tempo reale', b: 'Movimenti di pallet, UDC e asset monitorati con continuità lungo tutta la filiera.' },
        { icon: 'layers',   t: 'Buoni pallet / asset',         b: 'Ogni movimentazione diventa un credito tracciato, estinguibile per riconsegna o compensazione.' },
        { icon: 'shield',   t: 'Gestione asset danneggiati',   b: 'Segnalazione, stato, responsabilità e processi di recupero, sostituzione o addebito.' },
        { icon: 'database', t: 'Riconciliazione condivisa',    b: 'Dati affidabili e verificabili tra tutti gli attori, per un presidio amministrativo chiaro.' },
        { icon: 'cube',     t: 'Multi-asset configurabile',    b: 'Pallet, ganci, box, cassette, rack e supporti speciali: una piattaforma per ogni UDC.' },
        { icon: 'link',     t: 'Integrazione ERP',             b: 'Dialogo nativo con i principali ERP e gestionali, senza duplicazioni di dato.' },
      ],
      sectors: [
        { t: 'Manifatturiero',         b: 'Già adottato da primarie aziende dei settori lattiero-caseario e salumi/formaggi.', tag: 'Food · UDC',    href: '/azienda' },
        { t: 'Logistica & Trasporti',  b: 'Piattaforme logistiche e distributori con elevati volumi di unità di carico.',      tag: 'Piattaforme',   href: '/azienda' },
        { t: 'Retail & Distribuzione', b: 'Reti distributive che gestiscono asset riutilizzabili tra più punti di consegna.',  tag: 'Distribuzione', href: '/azienda' },
      ],
      integrations: [
        { t: 'ERP & gestionali', v: 'Integrazione nativa con i principali ERP e gestionali di mercato' },
        { t: 'Modalità',         v: 'Web-based · SaaS · accesso multi-dispositivo · aggiornamenti continui' },
        { t: 'Asset gestiti',    v: 'Pallet · ganci · box · cassette · bins · rack · supporti speciali' },
        { t: 'Output',           v: 'Buoni asset · riconciliazioni · compensazioni · report di controllo' },
      ],
      faq: [
        { q: 'LogiTrace gestisce solo i pallet?',
          a: 'No. Pur essendo oggi molto utilizzato per i pallet, LogiTrace è concepito per qualsiasi UDC o asset logistico riutilizzabile: ganci (es. trasporto prosciutti), box e contenitori per farmaceutico e sanitario, cassette, bins, rack e supporti speciali.' },
        { q: 'Come funzionano i buoni pallet / buoni asset?',
          a: 'A ogni consegna LogiTrace genera automaticamente un buono che trasforma la movimentazione in un credito tracciato. Il buono si estingue con la riconsegna della stessa quantità di asset oppure tramite meccanismi di compensazione tra le parti.' },
        { q: 'Si integra con il nostro ERP?',
          a: "Sì. LogiTrace è progettato per integrarsi con i principali ERP e gestionali di mercato, inserendosi nei processi esistenti e valorizzando gli investimenti già fatti. È inoltre configurabile su esigenze operative e settoriali specifiche." },
        { q: "Quanto è rapido il ritorno dell'investimento?",
          a: 'Particolarmente rapido: deriva dalla riduzione delle perdite di asset, dal calo delle contestazioni, dalla semplificazione amministrativa e dal miglioramento generale dell\'efficienza operativa.' },
      ],
    },
    en: {
      title: 'Pallet & Asset Traceability',
      eyebrow: 'Solution · Pallet & Asset Traceability',
      pitch: 'Complete traceability of pallets, LHUs and reusable assets, with real-time visibility and reconciliation across all supply chain stakeholders.',
      intro: 'Managing pallets and, more broadly, load handling units (LHUs) and reusable assets is one of the most sensitive areas of business processes: poor visibility over flows, mismatches between delivered, returned and in-stock quantities, economic losses and disputes among supply chain stakeholders. LogiTrace is the LogiExpert solution that transforms a dispersive process into an organised, transparent and fully controlled system.',
      statsLabel: 'In brief',
      stats: [
        { v: 'SaaS', l: 'Web-based architecture, rapid activation' },
        { v: 'ERP',  l: 'Native integration with management systems' },
        { v: 'ROI',  l: 'Fast and measurable return on investment' },
      ],
      problems: [
        { t: 'Limited flow visibility', b: 'Without structured tools, there is no clear, timely and shared view of asset movements among the various supply chain stakeholders.' },
        { t: 'Mismatches and unreturned assets', b: 'Recurring differences between quantities delivered, returned and actually in stock at customers, suppliers, carriers and logistics platforms.' },
        { t: 'Losses and disputes', b: 'Misplacements, dispersions and disputes that translate into economic losses, administrative costs and tension between parties.' },
        { t: 'Manual and non-integrated management', b: 'Spreadsheets and unintegrated tools that do not communicate with business systems, limiting control and decision-making capacity.' },
      ],
      software: {
        name: 'LogiTrace',
        label: 'Software delivering the solution',
        desc: "Web-based SaaS platform for complete traceability and integrated management of reusable assets. Integrates with the main ERPs and management systems and is configurable on the company's actual flows. In addition to pallets, it manages hooks, boxes, crates, racks and any LHU requiring traceability, return and compensation.",
        bullets: [
          'Precise tracking of asset movements between companies, customers, distributors and logistics partners',
          'Real-time monitoring of quantities delivered, received and in stock for each party',
          'Automatic generation of pallet vouchers / asset vouchers at each delivery, as a tracked credit',
          'Voucher settlement via return delivery or compensation mechanisms between parties',
          'Management of damaged assets: reporting, status, responsibility, recovery or charge-back',
        ],
        sku: 'Web-based architecture · SaaS',
      },
      features: [
        { icon: 'radar',    t: 'Real-time traceability',     b: 'Pallet, LHU and asset movements monitored continuously throughout the supply chain.' },
        { icon: 'layers',   t: 'Pallet / asset vouchers',    b: 'Every movement becomes a tracked credit, settleable by return delivery or compensation.' },
        { icon: 'shield',   t: 'Damaged asset management',   b: 'Reporting, status, responsibility and recovery, replacement or charge-back processes.' },
        { icon: 'database', t: 'Shared reconciliation',      b: 'Reliable and verifiable data among all stakeholders, for clear administrative oversight.' },
        { icon: 'cube',     t: 'Multi-asset configurable',   b: 'Pallets, hooks, boxes, crates, racks and special supports: one platform for every LHU.' },
        { icon: 'link',     t: 'ERP integration',            b: 'Native communication with the main ERPs and management systems, without data duplication.' },
      ],
      sectors: [
        { t: 'Manufacturing',          b: 'Already adopted by major companies in the dairy and cured meats/cheese sectors.', tag: 'Food · LHU',    href: '/azienda' },
        { t: 'Logistics & Transport',  b: 'Logistics platforms and distributors with high volumes of load handling units.',   tag: 'Platforms',    href: '/azienda' },
        { t: 'Retail & Distribution',  b: 'Distribution networks managing reusable assets across multiple delivery points.',  tag: 'Distribution', href: '/azienda' },
      ],
      integrations: [
        { t: 'ERP & management systems', v: 'Native integration with the main ERPs and management systems on the market' },
        { t: 'Mode',                     v: 'Web-based · SaaS · multi-device access · continuous updates' },
        { t: 'Managed assets',           v: 'Pallets · hooks · boxes · crates · bins · racks · special supports' },
        { t: 'Output',                   v: 'Asset vouchers · reconciliations · compensations · control reports' },
      ],
      faq: [
        { q: 'Does LogiTrace only manage pallets?',
          a: 'No. Although widely used for pallets today, LogiTrace is designed for any LHU or reusable logistics asset: hooks (e.g. for ham transport), boxes and containers for pharmaceutical and healthcare, crates, bins, racks and special supports.' },
        { q: 'How do pallet / asset vouchers work?',
          a: 'At each delivery, LogiTrace automatically generates a voucher that turns the movement into a tracked credit. The voucher is settled by returning the same quantity of assets or through compensation mechanisms between the parties.' },
        { q: 'Does it integrate with our ERP?',
          a: 'Yes. LogiTrace is designed to integrate with the main ERPs and management systems on the market, fitting into existing processes and leveraging investments already made. It is also configurable for specific operational and sector requirements.' },
        { q: 'How fast is the return on investment?',
          a: 'Particularly fast: it derives from reduced asset losses, fewer disputes, administrative simplification and an overall improvement in operational efficiency.' },
      ],
    },
  },

  'proof-of-delivery': {
    n: '02',
    slug: '/soluzioni/proof-of-delivery',
    icon: 'send',
    it: {
      title: 'Proof of Delivery Digitale',
      eyebrow: 'Soluzione · Proof of Delivery',
      pitch: 'La consegna diventa un processo tracciato, certificato e integrato nei sistemi aziendali — senza documentazione cartacea.',
      intro: "La consegna è il punto di contatto diretto tra azienda e cliente finale, e uno dei momenti più critici del processo logistico: documentazione cartacea, informazioni non tempestive e assenza di evidenze oggettive generano ritardi amministrativi, contestazioni e perdita di controllo sull'esito. LogiPod digitalizza e struttura l'intero processo di consegna, garantendo tracciabilità, affidabilità e immediatezza delle informazioni.",
      statsLabel: 'In sintesi',
      stats: [
        { v: 'SaaS',      l: 'Web-based, operatori sul campo sempre connessi' },
        { v: 'Real-time', l: 'Evidenze disponibili subito ai sistemi aziendali' },
        { v: 'ERP',       l: 'Integrazione fluida con i gestionali' },
      ],
      problems: [
        { t: 'Documentazione cartacea', b: 'I documenti di consegna su carta rallentano la gestione amministrativa e si perdono o si danneggiano facilmente.' },
        { t: 'Assenza di evidenze oggettive', b: 'Senza firma, foto e dati contestuali ogni contestazione del cliente diventa difficile da gestire e documentare.' },
        { t: 'Informazioni non tempestive', b: 'Dati raccolti in modo non strutturato e non immediato, complessi da integrare nei sistemi aziendali.' },
        { t: 'Ritardi amministrativi', b: "La gestione documentale a valle della consegna allunga i tempi e riduce la visibilità sull'effettivo esito." },
      ],
      software: {
        name: 'LogiPod',
        label: 'Software che realizza la soluzione',
        desc: "Piattaforma web-based in modalità SaaS che trasforma la consegna in un processo tracciato, certificato e integrato nei flussi aziendali. Operatori sul campo e personale interno accedono in modo semplice e continuo; l'integrazione con i principali ERP rende le evidenze immediatamente disponibili.",
        bullets: [
          'Gestione digitale di tutte le fasi della consegna, senza documentazione cartacea',
          'Acquisizione di firme elettroniche, immagini, note operative e dati contestuali sul campo',
          'Registrazione puntuale di data, ora e informazioni sull\'esecuzione delle attività',
          'Certificazione chiara e verificabile dell\'esito di consegne e operazioni',
          'Evidenze immediatamente disponibili ai sistemi aziendali e agli utenti autorizzati',
        ],
        sku: 'Architettura web-based · SaaS',
      },
      features: [
        { icon: 'send',     t: 'Firma elettronica',       b: "Firma del destinatario acquisita digitalmente sul campo e allegata alla consegna." },
        { icon: 'scan',     t: 'Foto ed evidenze',        b: "Immagini, note operative e dati contestuali a certificazione dell'operazione svolta." },
        { icon: 'radar',    t: 'Data, ora e contesto',    b: "Ogni attività registrata con timestamp e informazioni puntuali sull'esecuzione." },
        { icon: 'shield',   t: 'Gestione contestazioni',  b: 'Evidenze digitali immediate per affrontare reclami in modo rapido e documentato.' },
        { icon: 'database', t: 'Esito certificato',       b: 'Conferma verificabile delle consegne, disponibile a sistemi e utenti autorizzati.' },
        { icon: 'link',     t: 'Integrazione ERP',        b: 'Dialogo fluido con i principali ERP e gestionali presenti in azienda.' },
      ],
      sectors: [
        { t: 'Logistica & Trasporti',  b: 'Flotte e reti di consegna che devono certificare ogni operazione sul campo.',   tag: 'Last mile',  href: '/azienda' },
        { t: 'Retail & Distribuzione', b: 'Riassortimento e consegne ai punti vendita con prova di consegna strutturata.', tag: 'B2B retail', href: '/azienda' },
        { t: 'Manifatturiero',         b: 'Consegne dirette a clienti e distributori con evidenze integrate nei sistemi.', tag: 'B2B direct', href: '/azienda' },
      ],
      integrations: [
        { t: 'ERP & gestionali', v: 'Integrazione con i principali ERP e gestionali di mercato' },
        { t: 'Modalità',         v: 'Web-based · SaaS · accesso continuo per operatori e backoffice' },
        { t: 'Evidenze',         v: 'Firma elettronica · foto · note · data/ora · dati contestuali' },
        { t: 'Output',           v: 'POD certificati · esiti consegna · documentazione anti-contestazione' },
      ],
      faq: [
        { q: 'LogiPod elimina davvero la carta nelle consegne?',
          a: 'Sì. Tutte le fasi del processo di consegna sono gestite in modalità digitale: firma elettronica, foto, note e dati contestuali vengono acquisiti direttamente sul campo, eliminando la documentazione cartacea.' },
        { q: 'Come aiuta nella gestione delle contestazioni?',
          a: 'La disponibilità di evidenze digitali immediate e strutturate (firma, immagini, data/ora) permette di affrontare reclami in modo rapido, preciso e documentato, riducendo il rischio di controversie.' },
        { q: 'Le evidenze sono subito disponibili ai nostri sistemi?',
          a: 'Sì. LogiPod rende le informazioni immediatamente disponibili ai sistemi aziendali e agli utenti autorizzati, grazie all\'integrazione con i principali ERP e gestionali.' },
        { q: 'Che tipo di architettura ha LogiPod?',
          a: "È una piattaforma web-based erogata in modalità SaaS: implementazione rapida, aggiornamenti costanti, accesso continuo e scalabile per gli operatori sul campo e per il personale aziendale." },
      ],
    },
    en: {
      title: 'Digital Proof of Delivery',
      eyebrow: 'Solution · Proof of Delivery',
      pitch: 'The delivery becomes a tracked, certified process integrated into business systems — without paper documentation.',
      intro: 'Delivery is the direct point of contact between company and end customer, and one of the most critical moments in the logistics process: paper documentation, untimely information and the absence of objective evidence generate administrative delays, disputes and loss of control over the outcome. LogiPod digitalises and structures the entire delivery process, ensuring traceability, reliability and immediacy of information.',
      statsLabel: 'In brief',
      stats: [
        { v: 'SaaS',      l: 'Web-based, field operators always connected' },
        { v: 'Real-time', l: 'Evidence immediately available to business systems' },
        { v: 'ERP',       l: 'Smooth integration with management systems' },
      ],
      problems: [
        { t: 'Paper documentation', b: 'Paper delivery documents slow down administrative management and are easily lost or damaged.' },
        { t: 'Absence of objective evidence', b: 'Without signature, photos and contextual data, every customer dispute becomes difficult to handle and document.' },
        { t: 'Untimely information', b: 'Data collected in an unstructured and non-immediate way, complex to integrate into business systems.' },
        { t: 'Administrative delays', b: 'Document management downstream of delivery extends processing times and reduces visibility over the actual outcome.' },
      ],
      software: {
        name: 'LogiPod',
        label: 'Software delivering the solution',
        desc: 'Web-based SaaS platform that transforms delivery into a tracked, certified process integrated into business flows. Field operators and internal staff access it simply and continuously; integration with the main ERPs makes evidence immediately available.',
        bullets: [
          'Digital management of all delivery phases, without paper documentation',
          'Acquisition of electronic signatures, images, operational notes and contextual data in the field',
          'Precise recording of date, time and information on activity execution',
          'Clear and verifiable certification of delivery outcomes and operations',
          'Evidence immediately available to business systems and authorised users',
        ],
        sku: 'Web-based architecture · SaaS',
      },
      features: [
        { icon: 'send',     t: 'Electronic signature',   b: 'Recipient signature acquired digitally in the field and attached to the delivery.' },
        { icon: 'scan',     t: 'Photos and evidence',    b: 'Images, operational notes and contextual data to certify the operation performed.' },
        { icon: 'radar',    t: 'Date, time and context', b: 'Every activity recorded with a timestamp and precise information on execution.' },
        { icon: 'shield',   t: 'Dispute management',     b: 'Immediate digital evidence to handle complaints quickly and in a documented way.' },
        { icon: 'database', t: 'Certified outcome',      b: 'Verifiable confirmation of deliveries, available to systems and authorised users.' },
        { icon: 'link',     t: 'ERP integration',        b: 'Smooth communication with the main ERPs and management systems in-house.' },
      ],
      sectors: [
        { t: 'Logistics & Transport',  b: 'Fleets and delivery networks that need to certify every field operation.',                 tag: 'Last mile',  href: '/azienda' },
        { t: 'Retail & Distribution',  b: 'Restocking and point-of-sale deliveries with structured proof of delivery.',              tag: 'B2B retail', href: '/azienda' },
        { t: 'Manufacturing',          b: 'Direct deliveries to customers and distributors with evidence integrated into systems.',  tag: 'B2B direct', href: '/azienda' },
      ],
      integrations: [
        { t: 'ERP & management systems', v: 'Integration with the main ERPs and management systems on the market' },
        { t: 'Mode',                     v: 'Web-based · SaaS · continuous access for operators and back-office' },
        { t: 'Evidence',                 v: 'Electronic signature · photos · notes · date/time · contextual data' },
        { t: 'Output',                   v: 'Certified PODs · delivery outcomes · anti-dispute documentation' },
      ],
      faq: [
        { q: 'Does LogiPod really eliminate paper in deliveries?',
          a: 'Yes. All phases of the delivery process are managed digitally: electronic signature, photos, notes and contextual data are captured directly in the field, eliminating paper documentation.' },
        { q: 'How does it help with dispute management?',
          a: 'The availability of immediate and structured digital evidence (signature, images, date/time) allows complaints to be handled quickly, accurately and in a documented way, reducing the risk of disputes.' },
        { q: 'Is the evidence immediately available to our systems?',
          a: "Yes. LogiPod makes information immediately available to business systems and authorised users, thanks to integration with the main ERPs and management systems." },
        { q: 'What architecture does LogiPod have?',
          a: 'It is a web-based platform delivered in SaaS mode: rapid implementation, continuous updates, and scalable continuous access for field operators and company staff.' },
      ],
    },
  },

  'wms': {
    n: '03',
    slug: '/soluzioni/wms',
    icon: 'database',
    it: {
      title: 'Warehouse Management System',
      eyebrow: 'Soluzione · WMS (in evoluzione)',
      pitch: 'Il magazzino da area esecutiva a nodo strategico: controllo, tracciabilità e continuità informativa dal ricevimento alla spedizione.',
      intro: "Il magazzino è oggi una delle aree più strategiche per l'efficienza della supply chain: incide su qualità del servizio, produttività, precisione inventariale e capacità di risposta al mercato. LogiStock è il Warehouse Management System in evoluzione di LogiExpert, pensato per gestire in modo strutturato i processi di magazzino con un'architettura web-based e cloud-native (SaaS), integrata nell'ecosistema logistico e gestionale.",
      statsLabel: 'In sintesi',
      stats: [
        { v: 'Cloud',     l: 'Architettura web-based, cloud-native · SaaS' },
        { v: 'Real-time', l: 'Visibilità inventariale continua' },
        { v: 'ERP',       l: 'Integrazione con gestionali e automazione' },
      ],
      problems: [
        { t: 'Magazzino non governato', b: "Trattare il magazzino come semplice area esecutiva, senza controllo strutturato, ne limita l'efficienza complessiva." },
        { t: 'Complessità dei flussi', b: "Aumento delle referenze, pressione sui tempi di evasione e flussi articolati rendono ingestibile l'operatività senza un WMS." },
        { t: 'Discrepanze inventariali', b: 'Senza visibilità in tempo reale su cosa è disponibile e dove, crescono errori, stock-out e giacenze poco affidabili.' },
        { t: 'Discontinuità informativa', b: 'La mancanza di continuità tra inbound, stock e outbound frammenta i dati e rallenta le decisioni.' },
      ],
      software: {
        name: 'LogiStock',
        label: 'Software che realizza la soluzione',
        desc: "WMS in evoluzione, web-based e cloud-native (SaaS), pensato per presidiare l'intero ciclo operativo del magazzino — inbound, stock e outbound — con visibilità in tempo reale e integrazione nativa con ERP, gestionali e, dove necessario, tecnologie di automazione e robotica.",
        bullets: [
          'Inbound: ricevimento guidato, validazione dati, strategie di putaway, barcode scanning',
          'Visibilità inventariale real-time: bin e ubicazioni, giacenze, cycle counting / inventario ciclico',
          'Outbound: picking a onde e multi-ordine, task management, packing e shipping ottimizzati',
          'Gestione lotti, seriali, scadenze e regole di rotazione (FEFO / FIFO)',
          'Apertura ad aree avanzate: labor, slotting, cross-docking, kitting, resi, yard management',
        ],
        sku: 'Cloud-native · SaaS · in evoluzione',
      },
      features: [
        { icon: 'cube',     t: 'Inbound guidato',            b: 'Ricevimento, validazione e putaway strutturati, con barcode scanning fin dal primo ingresso merce.' },
        { icon: 'database', t: 'Stock in tempo reale',       b: "Bin e ubicazioni, giacenze e inventario ciclico per accuratezza senza fermare l'operatività." },
        { icon: 'send',     t: 'Outbound ottimizzato',       b: 'Picking a onde e multi-ordine, packing e shipping per più throughput e meno errori.' },
        { icon: 'shield',   t: 'Lotti, seriali, scadenze',   b: 'Batch e serial management, FEFO/FIFO ed expiry tracking per conformità e rintracciabilità.' },
        { icon: 'cog',      t: 'Aree a valore aggiunto',     b: 'Labor, slotting, cross-docking, kitting, resi e yard management in roadmap evolutiva.' },
        { icon: 'link',     t: 'Integrazione & automazione', b: 'Dialogo con ERP, gestionali e, dove serve, robot, conveyor e sistemi di automazione.' },
      ],
      sectors: [
        { t: 'Manifatturiero',         b: 'Magazzini di materie prime, semilavorati e prodotto finito con flussi articolati.', tag: 'MP · WIP · PF', href: '/azienda' },
        { t: 'Logistica & Trasporti',  b: 'Operatori logistici con elevati volumi e pressione sui tempi di evasione.',          tag: 'Throughput',    href: '/azienda' },
        { t: 'Retail & Distribuzione', b: 'Centri di distribuzione con alta rotazione e numerose referenze.',                   tag: 'DC',            href: '/azienda' },
      ],
      integrations: [
        { t: 'ERP & gestionali', v: 'Integrazione nativa con i principali ERP e gestionali di mercato' },
        { t: 'Automazione',      v: 'Apertura a robot · conveyor · sortation · Warehouse Execution System' },
        { t: 'Modalità',         v: 'Web-based · cloud-native · SaaS · aggiornamenti continui' },
        { t: 'Processi',         v: 'Inbound · stock & cycle counting · outbound · lotti/seriali · FEFO/FIFO' },
      ],
      faq: [
        { q: 'LogiStock è già disponibile?',
          a: "LogiStock è il WMS di LogiExpert in evoluzione: nasce con architettura web-based e cloud-native (SaaS) e copre progressivamente l'intero ciclo di magazzino, dal ricevimento alla spedizione. Il perimetro funzionale viene esteso in modo coerente con le best practice di mercato." },
        { q: 'È una soluzione cloud?',
          a: 'Sì. LogiStock è impostato in logica web-based e SaaS cloud-native, per garantire accessibilità, continuità operativa, scalabilità e aggiornamenti continui, con un impatto minimo sull\'infrastruttura IT esistente.' },
        { q: "Copre sia l'inbound sia l'outbound?",
          a: "Sì. Presidia il ricevimento guidato e il putaway in ingresso, la visibilità inventariale in tempo reale, e in uscita il picking (a onde e multi-ordine), il packing e lo shipping, con gestione di lotti, seriali e regole FEFO/FIFO." },
        { q: 'Si integra con ERP e con sistemi di automazione?',
          a: 'Sì. LogiStock è pensato per integrarsi con i principali ERP e gestionali e per dialogare, dove necessario, con tecnologie di automazione e robotica (robot, conveyor, sortation, WES), come punto di coordinamento tra persone, mezzi, dispositivi e dati.' },
      ],
    },
    en: {
      title: 'Warehouse Management System',
      eyebrow: 'Solution · WMS (in development)',
      pitch: 'The warehouse from execution area to strategic node: control, traceability and information continuity from receiving to shipping.',
      intro: "The warehouse is today one of the most strategic areas for supply chain efficiency: it affects service quality, productivity, inventory accuracy and market responsiveness. LogiStock is LogiExpert's evolving Warehouse Management System, designed to manage warehouse processes in a structured way with a web-based, cloud-native (SaaS) architecture, integrated into the logistics and management ecosystem.",
      statsLabel: 'In brief',
      stats: [
        { v: 'Cloud',     l: 'Web-based, cloud-native architecture · SaaS' },
        { v: 'Real-time', l: 'Continuous inventory visibility' },
        { v: 'ERP',       l: 'Integration with management systems and automation' },
      ],
      problems: [
        { t: 'Ungoverned warehouse', b: 'Treating the warehouse as a simple execution area, without structured control, limits its overall efficiency.' },
        { t: 'Flow complexity', b: 'Growing SKU counts, pressure on fulfilment times and complex flows make operations unmanageable without a WMS.' },
        { t: 'Inventory discrepancies', b: 'Without real-time visibility on what is available and where, errors, stockouts and unreliable stock grow.' },
        { t: 'Information discontinuity', b: 'The lack of continuity between inbound, stock and outbound fragments data and slows decisions.' },
      ],
      software: {
        name: 'LogiStock',
        label: 'Software delivering the solution',
        desc: "Evolving WMS, web-based and cloud-native (SaaS), designed to oversee the entire operational warehouse cycle — inbound, stock and outbound — with real-time visibility and native integration with ERPs, management systems and, where needed, automation and robotics technologies.",
        bullets: [
          'Inbound: guided receiving, data validation, putaway strategies, barcode scanning',
          'Real-time inventory visibility: bins and locations, stock levels, cycle counting',
          'Outbound: wave and multi-order picking, task management, optimised packing and shipping',
          'Batch, serial, expiry and rotation rule management (FEFO / FIFO)',
          'Open to advanced areas: labour, slotting, cross-docking, kitting, returns, yard management',
        ],
        sku: 'Cloud-native · SaaS · in development',
      },
      features: [
        { icon: 'cube',     t: 'Guided inbound',          b: 'Structured receiving, validation and putaway with barcode scanning from the very first goods entry.' },
        { icon: 'database', t: 'Real-time stock',          b: 'Bins and locations, stock levels and cycle counting for accuracy without stopping operations.' },
        { icon: 'send',     t: 'Optimised outbound',       b: 'Wave and multi-order picking, packing and shipping for higher throughput and fewer errors.' },
        { icon: 'shield',   t: 'Batches, serials, expiry', b: 'Batch and serial management, FEFO/FIFO and expiry tracking for compliance and traceability.' },
        { icon: 'cog',      t: 'Value-added areas',        b: 'Labour, slotting, cross-docking, kitting, returns and yard management on the evolution roadmap.' },
        { icon: 'link',     t: 'Integration & automation', b: 'Communication with ERPs, management systems and, where needed, robots, conveyors and automation systems.' },
      ],
      sectors: [
        { t: 'Manufacturing',          b: 'Warehouses for raw materials, WIP and finished goods with complex flows.', tag: 'RM · WIP · FG', href: '/azienda' },
        { t: 'Logistics & Transport',  b: 'Logistics operators with high volumes and pressure on fulfilment times.',   tag: 'Throughput',   href: '/azienda' },
        { t: 'Retail & Distribution',  b: 'Distribution centres with high turnover and numerous SKUs.',                tag: 'DC',           href: '/azienda' },
      ],
      integrations: [
        { t: 'ERP & management systems', v: 'Native integration with the main ERPs and management systems on the market' },
        { t: 'Automation',               v: 'Open to robots · conveyors · sortation · Warehouse Execution System' },
        { t: 'Mode',                     v: 'Web-based · cloud-native · SaaS · continuous updates' },
        { t: 'Processes',                v: 'Inbound · stock & cycle counting · outbound · batch/serial · FEFO/FIFO' },
      ],
      faq: [
        { q: 'Is LogiStock available yet?',
          a: "LogiStock is LogiExpert's evolving WMS: built with a web-based, cloud-native (SaaS) architecture, it progressively covers the entire warehouse cycle, from receiving to shipping. The functional perimeter is extended in line with market best practices." },
        { q: 'Is it a cloud solution?',
          a: 'Yes. LogiStock is designed as a web-based and cloud-native SaaS solution, to ensure accessibility, operational continuity, scalability and continuous updates, with minimal impact on existing IT infrastructure.' },
        { q: 'Does it cover both inbound and outbound?',
          a: 'Yes. It handles guided receiving and putaway on the inbound side, real-time inventory visibility, and on the outbound side: picking (wave and multi-order), packing and shipping, with batch, serial and FEFO/FIFO rule management.' },
        { q: 'Does it integrate with ERPs and automation systems?',
          a: 'Yes. LogiStock is designed to integrate with the main ERPs and management systems and to communicate, where needed, with automation and robotics technologies (robots, conveyors, sortation, WES), acting as a coordination point between people, machines, devices and data.' },
      ],
    },
  },

  'aidc-mobility': {
    n: '04',
    slug: '/soluzioni/aidc-mobility',
    icon: 'scan',
    it: {
      title: 'Soluzioni AIDC & Mobility',
      eyebrow: 'Soluzione · AIDC & Mobility',
      pitch: 'Identificazione automatica e mobilità industriale, hardware end-to-end.',
      intro: "AIDC (Automatic Identification & Data Capture) e mobility industriale sono il sottostrato fisico di ogni soluzione software. LogiExpert è system integrator certificato Zebra, Honeywell e Datalogic: scegliamo, configuriamo e manuteniamo l'hardware adeguato al processo.",
      stats: [
        { v: 'AIDC', l: 'Identificazione automatica integrata nel processo' },
        { v: 'SLA',  l: 'Assistenza on-site su tutto il territorio italiano' },
        { v: 'MDM',  l: 'Zero-touch provisioning e gestione remota device' },
      ],
      problems: [
        { t: 'Hardware sotto-dimensionato',                b: "Terminali consumer in ambienti industriali che si rompono ogni 3 mesi." },
        { t: 'Configurazione manuale device a device',     b: "IT che spende settimane a configurare ogni nuovo terminale prima di consegnarlo all'operatore." },
        { t: 'Manutenzione non gestita',                   b: 'Quando un device si rompe, fermo macchina di giorni senza un canale di assistenza dedicato.' },
        { t: 'Standard frammentati',                       b: 'Barcode, RFID, NFC, voice, QR: ogni reparto ha scelto la propria tecnologia. Niente coerenza.' },
      ],
      software: {
        name: 'Hardware partner',
        label: 'Hardware che realizza la soluzione',
        desc: "Non un software proprietario, ma il nostro pacchetto di system integration su hardware certificato: scelta, configurazione MDM, deployment, manutenzione preventiva e correttiva con SLA on-site.",
        bullets: [
          'Terminali rugged Android · Zebra · Honeywell · Datalogic',
          'Stampanti industriali ZPL · termiche · etichette · ricevute',
          'Lettori barcode · RFID UHF · NFC',
          'MDM (SOTI · 42Gears · Microsoft Intune) per zero-touch provisioning',
          'SLA on-site 4h / 8h / next-business-day',
        ],
        sku: 'AIDC-2025',
      },
      features: [
        { icon: 'scan',    t: 'Barcode 1D · 2D',     b: 'Lettori industriali per ogni profondità di campo. Ambienti polverosi inclusi.' },
        { icon: 'rfid',    t: 'RFID UHF · NFC',      b: 'Tag passivi UHF per inventario massivo. NFC per autenticazione operatore.' },
        { icon: 'printer', t: 'Stampa industriale',  b: 'Etichette resistenti a temperatura, umidità, abrasione, agenti chimici.' },
        { icon: 'cube',    t: 'Voice picking',       b: "Headset per operatori con le mani impegnate. Riduce errori e migliora la produttività." },
        { icon: 'cog',     t: 'MDM zero-touch',      b: 'Device che si configurano da soli al primo boot. Niente IT manuale.' },
        { icon: 'shield',  t: 'Manutenzione su SLA', b: 'Helpdesk Italia, intervento on-site 4h sui contratti premium.' },
      ],
      sectors: [
        { t: 'Manifatturiero',         b: 'Terminali a bordo impianto. Stampanti etichette di lotto.',  tag: 'Linea · QC',  href: '/azienda' },
        { t: 'Logistica & Trasporti',  b: 'Terminali per magazziniere e per corriere.',                  tag: 'WMS · POD',   href: '/azienda' },
        { t: 'Retail & Distribuzione', b: 'Terminali per punto vendita e per inventario ciclico.',      tag: 'POS · STORE', href: '/azienda' },
      ],
      integrations: [
        { t: 'Terminali', v: 'Zebra TC22/TC27/TC78 · Honeywell CT45/CK65 · Datalogic Memor 10/20/30' },
        { t: 'Stampanti', v: 'Zebra ZT411 · ZT231 · ZD230 · Honeywell PD45 · PC42' },
        { t: 'Lettori',   v: 'Zebra DS3608 · DS9908 · Honeywell Xenon · Datalogic PowerScan' },
        { t: 'MDM',       v: 'SOTI MobiControl · 42Gears SureMDM · Microsoft Intune · Samsung Knox' },
      ],
      faq: [
        { q: 'Vendete solo hardware o anche assistenza?',
          a: "Entrambi. La parte hardware è venduta sul nostro eCommerce B2B; l'assistenza (configurazione, manutenzione preventiva, helpdesk, intervento on-site) è offerta in contratti annuali con SLA differenziati: 4h, 8h o NBD (next-business-day) sul territorio italiano." },
        { q: "Posso integrare l'hardware AIDC con un software non vostro?",
          a: "Sì. I terminali e i lettori che vendiamo sono standard di mercato e si integrano con qualunque WMS, ERP o TMS. La nostra forza è la system integration: gestiamo il deployment, la configurazione MDM e la manutenzione, anche se il software applicativo è di terze parti." },
        { q: 'Cosa significa zero-touch deployment?',
          a: "Significa che il device, appena acceso per la prima volta, si auto-registra al server MDM e scarica configurazione, profili rete, certificati e applicazioni — senza alcun intervento manuale di IT. Lo facciamo via Zebra StageNow, Knox Mobile Enrollment, Android Zero-touch o iOS Apple Business Manager." },
        { q: "Che differenza c'è tra Zebra, Honeywell e Datalogic?",
          a: "Tutti e tre sono player industriali di prim'ordine. Zebra è leader sui terminali e sulla stampa; Honeywell ha il portfolio più completo sul cold-chain; Datalogic è italiano e ha condizioni privilegiate sui lettori fissi industriali. Consigliamo il brand in base al caso d'uso, non al margine commerciale." },
      ],
    },
    en: {
      title: 'AIDC & Mobility Solutions',
      eyebrow: 'Solution · AIDC & Mobility',
      pitch: 'Automatic identification and industrial mobility, end-to-end hardware.',
      intro: "AIDC (Automatic Identification & Data Capture) and industrial mobility are the physical layer beneath every software solution. LogiExpert is a certified Zebra, Honeywell and Datalogic system integrator: we select, configure and maintain the hardware best suited to your process.",
      stats: [
        { v: 'AIDC', l: 'Automatic identification integrated in the process' },
        { v: 'SLA',  l: 'On-site support across the whole of Italy' },
        { v: 'MDM',  l: 'Zero-touch provisioning and remote device management' },
      ],
      problems: [
        { t: 'Undersized hardware',                    b: 'Consumer terminals in industrial environments that break every 3 months.' },
        { t: 'Manual device-by-device configuration',  b: 'IT teams spending weeks configuring every new terminal before handing it to the operator.' },
        { t: 'Unmanaged maintenance',                  b: 'When a device breaks, days of downtime with no dedicated support channel.' },
        { t: 'Fragmented standards',                   b: 'Barcode, RFID, NFC, voice, QR: each department chose its own technology. No consistency.' },
      ],
      software: {
        name: 'Hardware partner',
        label: 'Hardware delivering the solution',
        desc: 'Not proprietary software, but our system integration package on certified hardware: selection, MDM configuration, deployment, preventive and corrective maintenance with on-site SLA.',
        bullets: [
          'Rugged Android terminals · Zebra · Honeywell · Datalogic',
          'Industrial ZPL printers · thermal · labels · receipts',
          'Barcode readers · RFID UHF · NFC',
          'MDM (SOTI · 42Gears · Microsoft Intune) for zero-touch provisioning',
          'On-site SLA 4h / 8h / next-business-day',
        ],
        sku: 'AIDC-2025',
      },
      features: [
        { icon: 'scan',    t: 'Barcode 1D · 2D',    b: 'Industrial readers for any depth of field. Dusty environments included.' },
        { icon: 'rfid',    t: 'RFID UHF · NFC',     b: 'Passive UHF tags for mass inventory. NFC for operator authentication.' },
        { icon: 'printer', t: 'Industrial printing', b: 'Labels resistant to temperature, humidity, abrasion, chemical agents.' },
        { icon: 'cube',    t: 'Voice picking',       b: 'Headsets for operators with hands occupied. Reduces errors and improves productivity.' },
        { icon: 'cog',     t: 'MDM zero-touch',      b: 'Devices that configure themselves on first boot. No manual IT.' },
        { icon: 'shield',  t: 'SLA maintenance',     b: 'Italian helpdesk, on-site intervention within 4h on premium contracts.' },
      ],
      sectors: [
        { t: 'Manufacturing',          b: 'Terminals on the production line. Batch label printers.',  tag: 'Line · QC',   href: '/azienda' },
        { t: 'Logistics & Transport',  b: 'Terminals for warehouse staff and for couriers.',           tag: 'WMS · POD',   href: '/azienda' },
        { t: 'Retail & Distribution',  b: 'Terminals for point of sale and cycle counting.',          tag: 'POS · STORE', href: '/azienda' },
      ],
      integrations: [
        { t: 'Terminals', v: 'Zebra TC22/TC27/TC78 · Honeywell CT45/CK65 · Datalogic Memor 10/20/30' },
        { t: 'Printers',  v: 'Zebra ZT411 · ZT231 · ZD230 · Honeywell PD45 · PC42' },
        { t: 'Readers',   v: 'Zebra DS3608 · DS9908 · Honeywell Xenon · Datalogic PowerScan' },
        { t: 'MDM',       v: 'SOTI MobiControl · 42Gears SureMDM · Microsoft Intune · Samsung Knox' },
      ],
      faq: [
        { q: 'Do you sell only hardware or also support?',
          a: "Both. The hardware side is sold on our B2B eCommerce; support (configuration, preventive maintenance, helpdesk, on-site intervention) is offered in annual contracts with tiered SLAs: 4h, 8h or NBD (next-business-day) across Italy." },
        { q: 'Can I integrate AIDC hardware with software that is not yours?',
          a: 'Yes. The terminals and readers we sell are market standards and integrate with any WMS, ERP or TMS. Our strength is system integration: we manage deployment, MDM configuration and maintenance, even when the application software is third-party.' },
        { q: 'What does zero-touch deployment mean?',
          a: 'It means the device, as soon as it is switched on for the first time, self-registers with the MDM server and downloads configuration, network profiles, certificates and applications — with no manual IT intervention. We do this via Zebra StageNow, Knox Mobile Enrollment, Android Zero-touch or iOS Apple Business Manager.' },
        { q: 'What is the difference between Zebra, Honeywell and Datalogic?',
          a: "All three are first-rate industrial players. Zebra leads on terminals and printing; Honeywell has the most complete portfolio for cold chain; Datalogic is Italian and has preferential conditions on industrial fixed readers. We recommend the brand based on the use case, not the commercial margin." },
      ],
    },
  },
};
